// Posts client: fetch posts.json with fallback
window.getPosts = async function() {
  try {
    const res = await fetch('/api/posts.json');
    if (!res.ok) throw new Error('network');
    const data = await res.json();
    return data;
  } catch (err) {
    // Fallback to embedded data (same content as posts.json) for file:// or unavailable servers
    return [
      {slug:'remote-first-companies',title:'Remote-First Companies',category:'Business',date:'2025-01-27',views:1200,tags:['remote-work','productivity'],img:'https://images.unsplash.com/photo-1556761175-b413da4baf72?w=1200',excerpt:'How distributed teams succeed in the modern workplace.',author:'Saidjafar T.',read:'5 min read',avatar:'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200',content:'<p>Distributed work has reshaped how companies hire and operate. This article explores the structures, tools, and cultural shifts needed to run fully remote teams.</p><p>Key practices include async-first communication, trust-based performance metrics, and well-designed onboarding.</p>'},
      {slug:'the-ai-revolution',title:'The AI Revolution',category:'Technology',date:'2025-01-26',views:3200,tags:['ai-ml','productivity'],img:'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=1200',excerpt:'How machine learning is changing everything.',author:'Michael Chen',read:'8 min read',avatar:'https://images.unsplash.com/photo-1545996124-1b5f63bd46a3?w=200',content:'<p>Machine learning is transforming industries from healthcare to finance. This piece outlines practical use-cases and what leaders should prioritize.</p><p>From model interpretability to data governance, the AI agenda is shifting fast.</p>'},
      {slug:'designing-a-sustainable-future',title:'Designing a Sustainable Future',category:'Design',date:'2025-01-25',views:800,tags:['sustainability'],img:'https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=1200',excerpt:'Green tech with beautiful UX.',author:'Emma Watson',read:'6 min read',avatar:'https://images.unsplash.com/photo-1544005311-3fed3d1f3f35?w=200',content:'<p>Design plays a pivotal role in sustainable tech. Learn how designers balance aesthetics and low-impact engineering.</p>'},
      {slug:'travel-tips-2025',title:'Travel Tips for 2025',category:'Travel',date:'2025-01-20',views:670,tags:['productivity'],img:'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=1200',excerpt:'Smart budgeting and off-the-beaten-path finds.',author:'Travel Team',read:'7 min read',avatar:'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=200',content:'<p>Travel smarter in 2025: tips on budgeting, unique stays, and slower travel to see more.</p>'},
      {slug:'education-reform-road-ahead',title:'Education Reform: The Road Ahead',category:'Education',date:'2024-12-10',views:540,tags:[],img:'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=1200',excerpt:'How accessible learning is reshaping careers.',author:'Education Desk',read:'6 min read',avatar:'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=200',content:'<p>Education is evolving—this article looks at policy shifts and practical programs making learning more accessible.</p>'},
      {slug:'healthy-habits-remote-workers',title:'Healthy Habits for Remote Workers',category:'Health',date:'2024-11-15',views:420,tags:['remote-work'],img:'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=1200',excerpt:'Simple routines to improve wellbeing while working from home.',author:'Wellness Team',read:'4 min read',avatar:'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=200',content:'<p>Small routines can markedly improve mental and physical health when working remotely. Try a 20-minute midday walk and scheduled break times.</p>'},
      {slug:'blockchain-beyond-crypto',title:'Blockchain Beyond Crypto',category:'Technology',date:'2024-10-05',views:890,tags:['ai-ml'],img:'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=1200',excerpt:'Real-world applications of distributed ledger technology.',author:'Tech Insights',read:'9 min read',avatar:'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200',content:'<p>Beyond speculation, blockchain can streamline provenance and supply chains when implemented thoughtfully.</p>'}
    ];
  }
};