# Generated by Django 5.2.9 on 2025-12-30 04:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpost_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=datetime.datetime(2025, 12, 30, 4, 45, 48, 72839, tzinfo=datetime.timezone.utc), upload_to='category_images/'),
            preserve_default=False,
        ),
    ]
