# Generated by Django 5.2.9 on 2026-03-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comment_ip_address_comment_user_agent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-published_date']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='view_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='first_name',
            field=models.CharField(default='Anonymous', max_length=50),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_approved',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='last_name',
            field=models.CharField(default='User', max_length=50),
        ),
        migrations.AddField(
            model_name='comment',
            name='visitor_id',
            field=models.CharField(db_index=True, default='00000000-0000-0000-0000-000000000000', max_length=36),
        ),
        migrations.AddField(
            model_name='dislike',
            name='visitor_id',
            field=models.CharField(db_index=True, default='00000000-0000-0000-0000-000000000000', max_length=36),
        ),
        migrations.AddField(
            model_name='like',
            name='visitor_id',
            field=models.CharField(db_index=True, default='00000000-0000-0000-0000-000000000000', max_length=36),
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='dislike',
            unique_together={('blog_post', 'visitor_id')},
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('blog_post', 'visitor_id')},
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='ip_address',
            field=models.GenericIPAddressField(db_index=True, default='127.0.0.1'),
        ),
        migrations.AlterField(
            model_name='dislike',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['-published_date'], name='blog_blogpo_publish_2a7cdd_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['slug'], name='blog_blogpo_slug_361555_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['is_featured', '-published_date'], name='blog_blogpo_is_feat_dc4aa6_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['category', '-published_date'], name='blog_blogpo_categor_cd2625_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['-view_count'], name='blog_blogpo_view_co_59f1ab_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['blog_post', '-created_at'], name='blog_commen_blog_po_317bbe_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['ip_address', 'created_at'], name='blog_commen_ip_addr_51ec3e_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['visitor_id'], name='blog_commen_visitor_ad1bc1_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['is_approved', '-created_at'], name='blog_commen_is_appr_171a86_idx'),
        ),
        migrations.AddIndex(
            model_name='dislike',
            index=models.Index(fields=['blog_post', 'visitor_id'], name='blog_dislik_blog_po_d9740f_idx'),
        ),
        migrations.AddIndex(
            model_name='dislike',
            index=models.Index(fields=['-created_at'], name='blog_dislik_created_08faaa_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['blog_post', 'visitor_id'], name='blog_like_blog_po_f87c10_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['-created_at'], name='blog_like_created_2c294a_idx'),
        ),
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='dislike',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='dislike',
            name='user_agent',
        ),
        migrations.RemoveField(
            model_name='like',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user_agent',
        ),
    ]
