# Generated by Django 5.2.9 on 2026-05-19 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blogpost_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('twitter', 'Twitter / X'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('copy_link', 'Copy Link'), ('native', 'Native Share')], db_index=True, max_length=20)),
                ('visitor_id', models.CharField(db_index=True, default='00000000-0000-0000-0000-000000000000', max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('blog_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='blog.blogpost')),
            ],
            options={
                'indexes': [models.Index(fields=['blog_post', 'platform'], name='blog_share_blog_po_848e8b_idx'), models.Index(fields=['-created_at'], name='blog_share_created_4038b5_idx')],
            },
        ),
    ]
